#!/usr/bin/env bash

[[ ! -x $(command -v git) ]] && echo "you're gonna need git installed" && exit 1

here=$(git rev-parse --show-toplevel)

pgr="delta --dark"
gfl="$HOME/.gitconfig.local"
if [[ ! $(command -v delta) ]] ; then
    echo "consider using https://github.com/dandavison/delta it's pretty nice"
elif ! grep -qe "$pgr" "$gfl" ; then
    [[ -f "$gfl" ]] && cp "$gfl" "$gfl.bak"
    printf -v setp '[core]\npager=%s\n' "$pgr"
    echo "$setp" > "$gfl"
    cat "$gfl.bak" >> "$gfl"
fi

src="$here/gitconfig"
dst="$HOME/.gitconfig"

[[ ! "$src" -ef "$dst" ]] && mv "$dst" "$dst.bak"

ln -sf "$src" "$dst"
